FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY DataModel/DataModel.csproj DataModel/
COPY Helper/Helper.csproj Helper/
COPY EBMS/EBMS.csproj EBMS/
COPY DSS/DSS.csproj DSS/
COPY MSS/MSS.csproj MSS/
COPY LCS/LCS.csproj LCS/
COPY SIAG/SIAG.csproj SIAG/
COPY CDB/CDB.csproj CDB/
COPY SuedtirolWein/SuedtirolWein.csproj SuedtirolWein/
COPY NINJA/NINJA.csproj NINJA/
COPY RAVEN/RAVEN.csproj RAVEN/
COPY STA/STA.csproj STA/
COPY LOOPTEC/LOOPTEC.csproj LOOPTEC/
COPY OdhNotifier/OdhNotifier.csproj OdhNotifier/
COPY PushServer/PushServer.csproj EBMS/
COPY JsonLDTransformer/JsonLDTransformer.csproj JsonLDTransformer/
COPY OdhApiCore/OdhApiCore.csproj OdhApiCore/
RUN dotnet restore OdhApiCore/OdhApiCore.csproj
COPY . .
WORKDIR /src/OdhApiCore
RUN dotnet build OdhApiCore.csproj -c Release -o /app

FROM build AS test
WORKDIR /src
RUN dotnet test --filter Category!=Integration OdhApiCore.sln

FROM build AS publish
RUN dotnet publish OdhApiCore.csproj -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
COPY OdhApiCore/xml/Weather.xml xml/
COPY OdhApiCore/xml/STACategories.xml xml/
COPY OdhApiCore/xml/BezirkWeather.xml xml/
COPY OdhApiCore/xml/RequestInterceptor.xml xml/
COPY OdhApiCore/appsettings.Production.json appsettings.json

# Expose the API port
EXPOSE 80

ENTRYPOINT ["dotnet", "OdhApiCore.dll"]
